### ISSUE TITLE
Internal doc migration - 404 on new landing page

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/docs-cloud-cdn#105]

**Comment by cyrichardson** [comment]
@meker12 Is there anything I can do to help with this?

**Comment by meker12** [comment]
@cyrichardson You can see the content deployed on 4/14 at this URL:   https://pages.github.rackspace.com/IX/internal-docs-cloud-cdn/

Currently, the docs-staging server that builds the content is down. I submitted a ticket to NebOps about it.  When the staging server is back up, we can fix the CDN internal build and make sure that you are able to update it by pushing content from this repo to the enterprise repo where content is published from.

**Comment by cyrichardson** [comment]
@meker12 Thank you!

**Comment by cyrichardson** [comment]
Updated made today, Margaret helped with access issues between the rackerlabs and github.rackspace.com. Followed Margaret's instructions for the process and updated the CDN Admin Guide.
