### ISSUE TITLE
CDN links on docs landing page are all 404

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-cdn#112]
Investigate why these links are all broken.  

https://developer.rackspace.com/docs/#docs-cloud-cdn  -- Direct link to menu with 404s.

Possible causes:

Bad redirect configuration
Build and deploy issues.

**Comment by cyrichardson** [comment]
@meker12 Thanks for this. I'm not seeing any broken links but maybe you have already fixed them???

**Comment by meker12** [comment]
Thanks for checking.  So the links to the API reference, Release Notes, and Developer Guide are returning 404.  It's because of a syntax error in the redirect file.  Fixed that.
