### ISSUE TITLE
QE refactored Rackspace CDN v1 API docs

### ISSUE THREAD

**Issue by cyrichardson** [rackerlabs/docs-cloud-cdn#121]
# Refactor API Guide: QE checklist

Use the following checklist to verify that API guide refactoring for each service. If you have questions, open a [docs-common issue](https://github.com/rackerlabs/docs-common/issues/new).  

Do the QE check against the PR submitted to the master repo.  Ask the person who did the refactoring to make you a collaborator on their fork in case you want to submit a PR to correct something. 

When you build the refactored Sphinx project, use the ``make clean html`` command to build chunked content. 

- [x] Review the [Strider build log](https://build.developer.rackspace.com/) for errors. Notify author about any issues.
- [x] Check for broken links.
- [x] Verify that navigation matches the [API Guide template](https://staging.developer.rackspace.com/staging.horse/build-2ecafb8a99/docs/api-doc-template/).
- [x] Check the *API reference* section to verify that the methods for each resource are in a single topic.
- [x] Check the *General API information* topics to make sure they match the common content where possible.
- [x] Check the *Authentication* topic in the Getting started section to make sure it matches the [common template](https://github.com/rackerlabs/docs-common/blob/master/api-guide-template/getting-started/authenticate.rst).
- [x] Check ``conf.py`` to make sure it has the updates from the 
       [template](https://github.com/rackerlabs/docs-common/blob/master/api-guide-template/conf.py).
- [x] Verify that you can [build locally from source](https://github.com/rackerlabs/docs-rackspace/blob/master/doc/tools/build-from-source.rst).

**Comment by cyrichardson** [comment]
Check the branch the PR #120.
If you need to, you can check the refactoring checklist used in issue #117.

**Comment by cyrichardson** [comment]
Sending Karin a link to this issue to see if one of the RPC writers wants to take the QE steps.

**Comment by catlook** [comment]
Link check: 
general api, asolute limits. the table title “Absolute limits#” has the # set up as a link to itself, i think

**Comment by catlook** [comment]
same "#" link in table for date and time formats

**Comment by catlook** [comment]
same thing RBAC product roles and capabilities table

**Comment by catlook** [comment]
same thing RBAC multiproduct roles and permissions table

**Comment by catlook** [comment]
same thing RBAC example resolving permissions table

**Comment by catlook** [comment]
Titles with each operation title are showing up as self-referencing links, despite teh absence of code directives to do that

**Comment by catlook** [comment]
line 69 of conf. py ... should reference prduct not developer documentation i think

**Comment by catlook** [comment]
good to go...roll on!!
