### ISSUE TITLE
No documentation for purging all assets

### ISSUE THREAD

**Issue by venix1** [rackerlabs/docs-cloud-cdn#132]
If you review the [quickstart](https://developer.rackspace.com/docs/cdn/quickstart/) guide, there are instructions for purging the entire CDN.

`You can purge all assets for your service:

$ curl -X DELETE $ENDPOINT/services/{serviceId}/assets?all=true \
  -H "X-Auth-Token: $TOKEN" \
  -H "Accept: application/json" | python -m json.tool`

This is not present under the assets section of the [reference document. ](https://developer.rackspace.com/docs/cdn/v1/api-reference/cdn-service-assets-operations/)

**Comment by cyrichardson** [comment]
@amitgandhinz Please check the API document and make sure that it is correct. 
@venix1 It's possible that the quickstart information for the SDK is not up to date because the SDK was done very early in Rackspace CDN development and has not been updated.

**Comment by amitgandhinz** [comment]
The API docs are correct.  If purging all, i recommend doing it with `?url=/*&hard=false`

**Comment by cyrichardson** [comment]
Thank you, @amitgandhinz!
@venix1 I opened issue for SDK doc check here https://github.com/rackerlabs/docs-quickstart/issues/133.

**Comment by cyrichardson** [comment]
Closing this issue against API docs. Opened issue again SDK quickstart docs to check it.
