### ISSUE TITLE
Please document error response for GET /ping API

### ISSUE THREAD

**Issue by ycombinator** [rackerlabs/docs-cloud-cdn#21]
Currently in http://docs.rackspace.com/cdn/api/v1.0/cdn-devguide/content/GET_getPing__ping_baseOperations.html, the success response (`204 No Content`) is documented. Please also document the error response (`500 Internal Server Error`) as well.

**Comment by cyrichardson** [comment]
500 and 503 published for ping using Sam Harwell's text.
