### ISSUE TITLE
Multi-factor auth

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-cdn#23]
Hi Catherine!
I submitted the pull request for CDN.  Let me know if you have any questions, problems, or suggestions regarding the content.

I am trying not to add too much content to the individual product guides to help us move in the direction of a common authentication section.  Also, the MFA stuff is still being developed and additional changes are coming soon.

Thanks,

Margaret

**Comment by cyrichardson** [comment]
Thanks Margaret! I'll get these in tomorrow afternoon.

Sent from my iPhone - typos may not be my own

On Jan 12, 2015, at 6:25 PM, "meker12" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Catherine!
I submitted the pull request for CDN. Let me know if you have any questions, problems, or suggestions regarding the content.

I am trying not to add too much content to the individual product guides to help us move in the direction of a common authentication section. Also, the MFA stuff is still being developed and additional changes are coming soon.

Thanks,

Margaret
