### ISSUE TITLE
Broken link - Under Service Operations - Create a Service there is a broken link

### ISSUE THREAD

**Issue by lauracly** [rackerlabs/docs-cloud-cdn#28]
There is a section of text on service_id (it looks like a note) there is a broken link to "List a Service".

Broken URL is: http://docs.rackspace.com/cdn/api/v1.0/cdn-devguide/content/GET_getService__services__service_id__servicesOperations.html

**Comment by cyrichardson** [comment]
Replaced with an internal reference: You can also retrieve ``service_id`` using :ref:`List a service <cdn-get-a-service>`.
