### ISSUE TITLE
Broken link - Under Service Operations - Update a Service there is a broken link

### ISSUE THREAD

**Issue by lauracly** [rackerlabs/docs-cloud-cdn#29]
In the content that starts: "To update a service..." the link to Create a Service at the end of the topic is broken.

Broken URL: http://docs.rackspace.com/cdn/api/v1.0/cdn-devguide/content/GET_getService__services__service_id__servicesOperations.html

**Comment by cyrichardson** [comment]
Link changed to internal reference: which are described in `Create a service <cdn-create-a-service>`.
