### ISSUE TITLE
Edits for release notes

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-cdn#33]
See the markup and comments in the attached Word doc for my suggested edits for the release notes. Please let me know if you have any questions. Thanks!

[Rackspace CDN Release Notes_editsKH.docx](https://github.com/rackerlabs/docs-cloud-cdn/files/30501/Rackspace.CDN.Release.Notes_editsKH.docx)

**Comment by cyrichardson** [comment]
Release Notes edits applied and Release Notes republished.
